
import React from 'react';

interface OutboundMail {
  id: string;
  recipient: string;
  subject: string;
  body: string;
  sentAt: string;
  status: 'DELIVERED';
}

interface MailLogProps {
  mails: OutboundMail[];
  isMailRelayActive: boolean;
}

const MailLog: React.FC<MailLogProps> = ({ mails, isMailRelayActive }) => {
  return (
    <div className="space-y-10 animate-in fade-in duration-500 pb-20">
      <header className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <div>
          <div className="flex items-center space-x-3 text-emerald-600 font-black text-[10px] uppercase tracking-[0.2em] mb-3">
             <i className="fas fa-envelope-circle-check"></i>
             <span>SYSTEM AUTOMATION / MAIL DISPATCH</span>
          </div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight uppercase">Outbound Mail Log</h1>
          <p className="text-slate-500 mt-2 font-medium max-w-2xl">
            Complete audit trail of autogenerated onboarding emails and system notifications dispatched to partners.
          </p>
        </div>

        <div className={`px-6 py-4 rounded-2xl border flex items-center space-x-4 transition-all ${isMailRelayActive ? 'bg-emerald-50 border-emerald-100 shadow-lg shadow-emerald-500/5' : 'bg-rose-50 border-rose-100 shadow-lg shadow-rose-500/5'}`}>
           <div className={`w-3 h-3 rounded-full ${isMailRelayActive ? 'bg-emerald-500 animate-pulse' : 'bg-rose-500 animate-ping'}`}></div>
           <div className="flex flex-col">
              <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1">Mail Protocol</span>
              <span className={`text-xs font-black uppercase ${isMailRelayActive ? 'text-emerald-700' : 'text-rose-700'}`}>
                 {!isMailRelayActive ? 'Action Required: Setup Key' : 'Relay Active (Resend)'}
              </span>
           </div>
        </div>
      </header>

      {!isMailRelayActive && (
        <section className="bg-indigo-600 rounded-[3rem] p-10 md:p-14 text-white shadow-2xl relative overflow-hidden animate-in slide-in-from-top-4 duration-700">
           <div className="absolute top-0 right-0 p-10 opacity-10 text-9xl pointer-events-none -translate-y-10 translate-x-10"><i className="fas fa-key"></i></div>
           <div className="relative z-10">
              <div className="flex items-center space-x-4 mb-8">
                 <div className="px-4 py-2 bg-white/20 backdrop-blur-md rounded-xl text-[10px] font-black uppercase tracking-widest border border-white/20">Onboarding Protocol</div>
                 <h2 className="text-2xl md:text-3xl font-black tracking-tight">Finalize Mail Integration</h2>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                 <Step number="1" title="Create API Key" desc="Click '+ Create API Key' in your Resend Dashboard. Set permissions to 'Full Access'." />
                 <Step number="2" title="Copy Secret String" desc="Copy the key immediately. It will start with 're_'. Do not use the DNS key (p=)." />
                 <Step number="3" title="Inject Variable" desc="Add 'RESEND_API_KEY' to your hosting environment variables and redeploy." />
              </div>
              
              <div className="mt-12 flex flex-col sm:flex-row items-center gap-6 pt-10 border-t border-white/10">
                 <a 
                   href="https://resend.com/api-keys" 
                   target="_blank" 
                   rel="noopener noreferrer"
                   className="w-full sm:w-auto px-10 py-5 bg-white text-indigo-600 rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl hover:scale-105 active:scale-95 transition-all flex items-center justify-center space-x-3"
                 >
                    <i className="fas fa-external-link-alt"></i>
                    <span>Open Resend Keys Dashboard</span>
                 </a>
                 <p className="text-[11px] text-indigo-200 font-medium italic">
                    Note: System emails will only trigger once the relay is successfully authenticated.
                 </p>
              </div>
           </div>
        </section>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
         <StatCard label="Dispatched Today" value={mails.filter(m => new Date(m.sentAt).toDateString() === new Date().toDateString()).length.toString()} icon="fa-paper-plane" color="text-indigo-600" />
         <StatCard label="Delivery Rate" value={isMailRelayActive ? "100%" : "0%"} icon="fa-check-double" color="text-emerald-600" />
         <StatCard label="Relay Latency" value={isMailRelayActive ? "1.2s" : "N/A"} icon="fa-bolt" color="text-amber-600" />
      </div>

      <div className="bg-white rounded-[3rem] border border-slate-100 shadow-sm overflow-hidden">
        <div className="p-8 border-b border-slate-50 flex justify-between items-center bg-slate-50/30">
           <h3 className="text-xl font-black text-slate-900">Dispatch History</h3>
           <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">{mails.length} Emails Sent</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
             <thead className="bg-white border-b border-slate-50 text-[10px] font-black text-slate-400 uppercase tracking-widest">
               <tr>
                 <th className="py-6 px-10">Recipient</th>
                 <th className="py-6 px-10">Subject</th>
                 <th className="py-6 px-10">Sent Timestamp</th>
                 <th className="py-6 px-10 text-right">Status</th>
               </tr>
             </thead>
             <tbody className="divide-y divide-slate-50">
               {mails.length === 0 ? (
                 <tr>
                   <td colSpan={4} className="py-24 text-center text-slate-300 font-bold uppercase text-xs italic tracking-widest">
                     {isMailRelayActive ? "The system hasn't dispatched any automated emails yet." : "Waiting for mail protocol activation..."}
                   </td>
                 </tr>
               ) : [...mails].reverse().map(mail => (
                 <tr key={mail.id} className="hover:bg-slate-50/50 transition-colors group">
                   <td className="py-6 px-10">
                      <div className="flex flex-col">
                        <span className="font-black text-slate-900">{mail.recipient}</span>
                        <span className="text-[9px] text-slate-400 font-black uppercase tracking-tighter">Landlord Onboarding</span>
                      </div>
                   </td>
                   <td className="py-6 px-10">
                      <p className="text-sm font-bold text-slate-600 group-hover:text-indigo-600 transition-colors">{mail.subject}</p>
                   </td>
                   <td className="py-6 px-10">
                      <span className="text-xs font-medium text-slate-400">{new Date(mail.sentAt).toLocaleString()}</span>
                   </td>
                   <td className="py-6 px-10 text-right">
                      <span className="px-3 py-1 bg-emerald-50 text-emerald-600 text-[9px] font-black uppercase tracking-widest rounded-lg border border-emerald-100">
                         {mail.status}
                      </span>
                   </td>
                 </tr>
               ))}
             </tbody>
          </table>
        </div>
      </div>

      <div className="bg-[#0f172a] p-10 rounded-[3.5rem] text-white shadow-2xl relative overflow-hidden">
         <div className="absolute top-0 right-0 p-10 opacity-10 text-8xl pointer-events-none"><i className="fas fa-bolt-lightning"></i></div>
         <h4 className="text-xl font-black mb-4 flex items-center">
            <i className="fas fa-robot mr-3 text-emerald-400"></i>
            Automated Protocol Active
         </h4>
         <p className="text-slate-400 text-sm font-medium max-w-2xl leading-relaxed">
           Our system uses automated dispatch triggers. When an asset is approved in the System Requests queue, the engine generates a secure, unique onboarding link and delivers it immediately via our verified Resend relay. No manual intervention is required for partner onboarding.
         </p>
      </div>
    </div>
  );
};

const Step: React.FC<{number: string, title: string, desc: string}> = ({ number, title, desc }) => (
  <div className="flex flex-col space-y-4">
     <div className="w-10 h-10 bg-white/10 rounded-xl flex items-center justify-center font-black text-white border border-white/10">{number}</div>
     <h4 className="text-lg font-black">{title}</h4>
     <p className="text-sm text-indigo-100 font-medium leading-relaxed">{desc}</p>
  </div>
);

const StatCard: React.FC<{label: string, value: string, icon: string, color: string}> = ({ label, value, icon, color }) => (
  <div className="bg-white p-8 rounded-[2.5rem] border border-slate-100 shadow-sm flex items-center justify-between group hover:border-indigo-100 transition-all">
     <div>
        <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">{label}</p>
        <h4 className="text-3xl font-black text-slate-900">{value}</h4>
     </div>
     <div className={`w-12 h-12 rounded-2xl bg-slate-50 flex items-center justify-center ${color} group-hover:scale-110 transition-transform`}>
        <i className={`fas ${icon}`}></i>
     </div>
  </div>
);

export default MailLog;
